export 'package:flutter/material.dart';
export 'package:flutter/services.dart';
export 'package:invoice_generator/view/screens/utills/globals.dart';
export 'package:invoice_generator/view/screens/pdf_page/pdf_page.dart';
export 'package:printing/printing.dart';
export 'package:invoice_generator/view/screens/utills/routes.dart';
export 'package:invoice_generator/view/screens/home_page/home_page.dart';
export 'package:invoice_generator/view/screens/invoice_page/heders_option/heders_option.dart';
export 'package:invoice_generator/view/screens/invoice_page/invoice_page.dart';
export 'package:invoice_generator/view/screens/invoice_page/products_option/product_option.dart';
export 'package:invoice_generator/view/screens/splash_screen/splash_screen.dart';
// export 'package:invoice_generator/view/screens/pdf_page/pdf_page.dart';
export 'package:invoice_generator/view/screens/utills/app_bar.dart';
